###test###

> *clojure.core/test*
> 
>     :::clojure
>     ([v])
> 
>   test [v] finds fn at key :test in var metadata and calls it,
>   presuming failure will throw exception
